# Generated by Django 5.0.9 on 2026-09-23 15:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('mensaje', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='NivelRiesgoARL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], max_length=3)),
                ('nombre', models.CharField(max_length=150)),
                ('multiplicador', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Nivel de riesgo ARL',
                'verbose_name_plural': 'Niveles de riesgo ARL',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RangoEmpleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('empleados_min', models.PositiveIntegerField()),
                ('empleados_max', models.PositiveIntegerField(blank=True, help_text="Vacío/null significa 'sin tope' (o más).", null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Rango de empleados',
                'verbose_name_plural': 'Rangos de empleados',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('nit', models.CharField(blank=True, max_length=30)),
                ('sector', models.CharField(blank=True, help_text='Texto libre, ej: "Comercio", "Construcción".', max_length=150)),
                ('numero_empleados', models.PositiveIntegerField()),
                ('nombre_contacto', models.CharField(max_length=200)),
                ('cargo_contacto', models.CharField(blank=True, max_length=150)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('telefono_contacto', models.CharField(blank=True, max_length=30)),
                ('comentario', models.TextField(blank=True)),
                ('precio_estimado_total', models.DecimalField(blank=True, decimal_places=2, help_text='Calculado en el servidor, nunca se confía en un valor enviado por el cliente.', max_digits=14, null=True)),
                ('estado', models.CharField(choices=[('NUEVA', 'Nueva'), ('CONTACTADO', 'Contactado'), ('CONVERTIDA', 'Convertida'), ('DESCARTADA', 'Descartada')], default='NUEVA', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nivel_riesgo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizador.nivelriesgoarl')),
                ('servicios', models.ManyToManyField(related_name='solicitudes', to='contenido.servicio')),
            ],
            options={
                'verbose_name': 'Solicitud de cotización',
                'verbose_name_plural': 'Solicitudes de cotización',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PrecioServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='contenido.servicio')),
                ('rango_empleados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='cotizador.rangoempleados')),
            ],
            options={
                'verbose_name': 'Precio de servicio',
                'verbose_name_plural': 'Precios de servicios',
                'unique_together': {('servicio', 'rango_empleados')},
            },
        ),
    ]
