# Generated by Django 5.0.9 on 2026-09-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('eslogan', models.CharField(max_length=300)),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
                ('historia_titulo', models.CharField(max_length=200)),
                ('historia_texto', models.TextField()),
                ('hero_titulo', models.CharField(max_length=200)),
                ('hero_subtitulo', models.CharField(max_length=300)),
                ('hero_imagen', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('whatsapp_numero', models.CharField(help_text='Solo dígitos con código de país, ej: 573001234567', max_length=20)),
                ('correo_contacto', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
        migrations.CreateModel(
            name='HitoHistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hito de historia',
                'verbose_name_plural': 'Hitos de historia',
                'ordering': ['orden', 'anio'],
            },
        ),
        migrations.CreateModel(
            name='LogoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='clientes/')),
                ('url_sitio', models.URLField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Logo de cliente',
                'verbose_name_plural': 'Logos de clientes',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('profesion', models.CharField(max_length=200)),
                ('tarjeta_profesional', models.CharField(blank=True, help_text='Número de tarjeta profesional / matrícula', max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipo/')),
                ('bio', models.TextField()),
                ('linkedin_url', models.URLField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Miembro del equipo',
                'verbose_name_plural': 'Miembros del equipo',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('icono', models.CharField(blank=True, help_text='Nombre de un icono, ej: shield-check', max_length=100)),
                ('descripcion_corta', models.CharField(max_length=300)),
                ('descripcion_larga', models.TextField()),
                ('normativa', models.CharField(blank=True, help_text='Ej: Resolución 0312 de 2019', max_length=200)),
                ('destacado', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden'],
            },
        ),
    ]
